name: Build

on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: windows-latest
    
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          java-version: 1.17

      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis

      - name: Cache SonarQube packages
        uses: actions/cache@v1
        with:
          path: ~\.sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube scanner
        id: cache-sonar-scanner
        uses: actions/cache@v1
        with:
          path: .\.sonar\scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          # Install SonarScanner.MSBuild
          Invoke-WebRequest -Uri https://github.com/SonarSource/sonar-scanner-msbuild/releases/download/6.0.0.81631/sonar-scanner-6.0.0.81631-net-framework.zip -OutFile sonar-scanner-msbuild.zip
          Expand-Archive -Path sonar-scanner-msbuild.zip -DestinationPath .\.sonar\scanner
          Remove-Item sonar-scanner-msbuild.zip
        
      - name: Setup Nuget
        uses: Nuget/setup-nuget@v1.0.5

      - name: Restore nuget packages
        run: nuget restore AddNumbers.sln

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Check SonarQube scanner installation
        run: |
          Get-ChildItem -Path .\.sonar\scanner -Recurse
          Get-ChildItem -Path .\.sonar\scanner -Filter SonarScanner.MSBuild.exe -ErrorAction SilentlyContinue
          Get-ChildItem -Path .\.sonar\scanner -Filter dotnet-sonarscanner -ErrorAction SilentlyContinue
      
          # Get .store directory
          $storeDirectory = ".\.sonar\scanner\.store"
          if (Test-Path $storeDirectory) {
            Get-ChildItem -Path $storeDirectory -Recurse -ErrorAction SilentlyContinue
          }
        shell: powershell

      - name: Build and analyze
        shell: powershell
        run: |
          .\.sonar\scanner\SonarScanner.MSBuild begin /key:"AddNumbers" /d:sonar.host.url="${{ secrets.SONAR_HOST_URL }}"
          
          MSBuild.exe AddNumbers.sln /t:Rebuild /p:configuration=Release /p:Platform=x64
          
          # 빌드 프로세스가 완료될 때까지 대기 
          $buildProcess = Get-Process -Name MSBuild -ErrorAction SilentlyContinue
          while ($buildProcess) {
            Start-Sleep -Seconds 5
            $buildProcess = Get-Process -Name MSBuild -ErrorAction SilentlyContinue
          }
          
          .\.sonar\scanner\SonarScanner.MSBuild end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
