name: SonarQube Ping Test

on: [push]

jobs:
  sonarqube_ping_test:
    runs-on: ubuntu-latest

    steps:
    - name: Check SonarQube Version
      run: curl -s -m 10 -X GET http://192.168.1.62:4093/api/server/version
