name: SonarQube Ping Test

on: [push]

jobs:
  sonarqube_ping_test:
    runs-on: windows-latest

    steps:
    - name: Check SonarQube Version
      run: Invoke-WebRequest -Uri http://192.168.1.62:4093/api/server/version
