name: SonarQube Ping Test

on:
  push:
    branches:
      - dev

jobs:
  ping_test:
    runs-on: ubuntu-latest
    
    steps:      
    - name: Check Port Connectivity
      run: nc -zvw5 121.143.247.161 443

    - name: Ping IP Address
      run: ping -c 5 121.143.247.161
