name: SonarQube Ping Test

on: [push]

jobs:
  sonarqube_ping_test:
    runs-on: windows-latest

    steps:
    - name: Check SonarQube Version
      run: Invoke-WebRequest -Uri "http://121.143.24.161"
